name: Practice make perfect
on:
  push:
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github))
      - name: Print ENV
        run: printenv
