name: Practice make perfect
on:
  push:
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  

      - name: Setup Node ENV
        uses: actions/setup-node@v4

      - name: Dump github Context
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT > github.txt

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo $JOB_CONTEXT > job.txt

      - name: Dump steps context
        env:
          STEP_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo $STEP_CONTEXT > step.txt

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo $RUNNER_CONTEXT > runner.txt

      - name: Dump vars context
        env:
          VAR_CONTEXT: ${{ toJSON(vars) }}
        run: |
          echo $VAR_CONTEXT > var.txt

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github))

      - name: Export value to Github ENV
        run: |
          echo 'YO=BRO' >> $GITHUB_ENV

      - name: Print ENV
        run: |
          printenv > env.txt

      - name: Output data
        id: output-data
        run: |
          the_secret=$((RANDOM))
          echo secret-number=$((RANDOM)) >> "$GITHUB_OUTPUT"

      - name: User Output
        run: |
          echo "the secret number is ${{ steps.output-data.outputs.secret-number }}"

      - name: Check steps context
        run: |
          echo "${{ toJSON(steps) }}"

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(process.env)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SecretsVariables
          path: "*.txt"

      - name: Change PWD
        working-directory: ./scripts
        run: |
          chmod +x hello.js
          pwd
          ls -la
          node ./hello.js
          

    
      - name: Check PWD
        run: |
          pwd
          ls -la

      
