name: Practice make perfect
on:
  push:
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ENV
        uses: actions/setup-node@v4
      - name: Dump Github Context
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT

      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo $JOB_CONTEXT

      - name: Dump Steps Context
        env:
          STEP_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo $STEP_CONTEXT

      - name: Dump Runner Context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo $RUNNER_CONTEXT

      - name: Dump SECRETS Context
        env:
          SECRET_CONTEXT: ${{ toJSON(secrets) }}
        run: |
          echo $SECRET_CONTEXT

      - name: Dump Runner Context
        env:
          VAR_CONTEXT: ${{ toJSON(vars) }}
        run: |
          echo $VAR_CONTEXT

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github))

      - name: Print ENV
        run: |
          printenv > env.txt

      - name: Output data
        id: output-data
        run: |
          the_secret=$((RANDOM))
          echo secret-number=$((RANDOM)) >> "$GITHUB_OUTPUT"

      - name: User Output
        run: |
          echo "the secret number is ${{ steps.output-data.outputs.secret-number }}"

      - name: Check steps context
        run: |
          echo "${{ toJSON(steps) }}"

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(process.env)

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: SecretsVariables
          path: "env.txt"
