name: Practice make perfect
on:
  push:
jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node ENV
        uses: actions/setup-node@v4
      - name: Echo Github Context
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT
      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github))
      - name: Print ENV
        run: |
          printenv
      - name: Check steps context
        run: |
          echo ${{ toJSON(steps) }}
      - name: Output data
        id: output-data
        run: |
          echo $((RANDOM)) >> "$GITHUB_OUTPUT"
      - name: User Output
        run: |
          echo "the secret number is ${{ steps.output-data.outputs.secret-number }}"
