name: Practice make perfect
on:
  push:

  workflow_call:
env:
  YO: BRO
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  first_job:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      "secret-number": ${{ steps.output-data.outputs.secret-number }}
      "steps": ${{ toJson(steps) }}
      "eenv": ${{ toJson(env) }}
    steps:
      - name: Check out the repository to the runner
        id: step_1
        uses: actions/checkout@v4

      - name: Setup Node ENV
        id: step_2
        uses: actions/setup-node@v4

      - name: Dump github Context
        id: step_3
        env:
          EVENT_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $EVENT_CONTEXT > github.json

      - name: Dump job context
        id: step_4
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: |
          echo $JOB_CONTEXT > job.json

      - name: Dump steps context
        id: step_5
        env:
          STEP_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo $STEP_CONTEXT > step.json

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: |
          echo $RUNNER_CONTEXT > runner.json

      - name: Dump vars context
        env:
          VAR_CONTEXT: ${{ toJSON(vars) }}
        run: |
          echo $VAR_CONTEXT > var.json

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(github))

      - name: Export value to Github ENV
        run: |
          echo 'YO=BRO' >> $GITHUB_ENV

      - name: Print ENV
        run: |
          printenv > env.txt

      - name: Output data
        id: output-data
        run: |
          the_secret=$((RANDOM))
          echo secret-number=$((RANDOM)) >> "$GITHUB_OUTPUT"

      - name: User Output
        run: |
          echo "the secret number is ${{ steps.output-data.outputs.secret-number }}"

      - name: Check steps context
        run: |
          echo "${{ toJSON(steps) }}"

      - name: Print github context by github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log(process.env)

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SecretsVariables
      #     path: "*.txt"

      - name: Create pseudo error
        continue-on-error: true
        run: |
          exit 127

      - name: Change PWD
        working-directory: ./scripts
        run: |
          chmod +x hello.js
          pwd
          ls -la
          node ./hello.js

      - name: Check PWD
        run: |
          pwd
          ls -la

  next_job:
    needs: first_job
    runs-on: ubuntu-latest
    env:
      HELLO: WORLD

    steps:
      - name: Setup Node ENV
        id: step_2
        uses: actions/setup-node@v4
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Printing
        run: |
          ls -la
          echo ${{hashFiles('**/package-lock.json')}}
          printenv
      - name: Use First Action
        id: first-action
        uses: ./.github/actions/first-action
      - name: Use First Script
        id: first-script
        uses: actions/github-script@v7
        with:
          script: |
            const { default: darling } = await import('${{ github.workspace }}/index.js');

            await darling({core, context, github});

      - name: Dump
        run: |
          echo "${{ toJson(steps) }}"
